# Generated by Django 4.2.7 on 2023-11-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('tipo_cuenta_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuenta_name', models.TextField()),
                ('moneda', models.TextField()),
            ],
            options={
                'db_table': 'tipo_cuenta',
                'managed': False,
            },
        ),
    ]
