# Generated by Django 4.2.7 on 2023-11-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nro_cuenta', models.IntegerField()),
                ('flag', models.TextField()),
                ('monto', models.IntegerField()),
                ('tipo_operacion', models.IntegerField()),
                ('hora', models.TimeField()),
            ],
            options={
                'db_table': 'movimientos',
                'managed': False,
            },
        ),
    ]
