# Generated by Django 4.2.7 on 2023-11-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('cvv', models.IntegerField(blank=True, null=True, unique=True)),
                ('fecha_de_otorgamiento', models.IntegerField(blank=True, null=True)),
                ('fecha_de_expiracion', models.IntegerField(blank=True, null=True)),
                ('tipo_tarjeta', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarjeta',
                'managed': False,
            },
        ),
    ]
